---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 11.16.4

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[exabgp::default]
    attributes:
