---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.6

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[exabgp::default]
    attributes:
  - name: source
    run_list:
      - recipe[exabgp::source]
    attributes:
