---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 13

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: pip
    run_list:
      - recipe[test::pip]
    attributes:
  - name: package
    run_list:
      - recipe[test::package]
    attributes:
