---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: 12.6

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-16.04

suites:
  - name: package
    run_list:
      - recipe[test::package]
    verifier:
      inspec_tests:
        - test/smoke/package
    attributes:
  - name: source
    run_list:
      - recipe[test::source]
    verifier:
      inspec_tests:
        - test/smoke/source
    attributes:
