sudo: required
services: docker

addons:
  apt:
    sources:
      - chef-stable-precise
    packages:
      - chefdk

env:
  matrix:
    - INSTANCE=default-ubuntu-1404
    - INSTANCE=default-ubuntu-1204
    - INSTANCE=source-ubuntu-1404
    - INSTANCE=source-ubuntu-1204

# Don't `bundle install` because we're using ChefDK
install: echo "skip bundle install"

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - /opt/chefdk/embedded/bin/chef gem install kitchen-docker

script:
  - /opt/chefdk/embedded/bin/chef --version
  - /opt/chefdk/embedded/bin/rubocop --version
  - /opt/chefdk/embedded/bin/rubocop
  - /opt/chefdk/embedded/bin/foodcritic --version
  - /opt/chefdk/embedded/bin/foodcritic . --exclude spec
  - /opt/chefdk/embedded/bin/rspec
  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

notifications:
  slack:
    secure: PTV/w6y8Rl7X0DYAt1p0Ez0FzT8y45HK785P0JYFpoOpjKM54682fDULuFL8LZGzXsyGt8A2btj+lVOo/HMWpFD7ho+K0+5tXolJ4f7GobNz+eKKrGRoOpGgfgKjDqzF44MEqa/W5kFBVLH7t6wW4OpwcaYAlGT4bgw3WONuAkI=
