sudo: required
dist: trusty

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

env:
  matrix:
    - INSTANCE=default-ubuntu-1404
    # - INSTANCE=default-ubuntu-1204
    # - INSTANCE=source-ubuntu-1404
    # - INSTANCE=source-ubuntu-1204

# Don't `bundle install` because we're using ChefDK
install: echo "skip bundle install"

before_script:
  # https://github.com/zuazo/kitchen-in-travis-native/issues/1#issuecomment-142230889
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef gem install kitchen-docker
  - chef gem install stove

script:
  - chef --version
  - rubocop --version
  - rubocop
  - foodcritic --version
  - foodcritic . --exclude spec
  - rspec
  # - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/embedded/bin/kitchen verify ${INSTANCE}

notifications:
  email: false
  slack:
    secure: "cNz3S0Iw6IWQOzP4IIwSbqMjhPYNOwb6w/9/G1G6YcRTUDEtBY/BwJMdOyMsI568GU+D94oQa7OXswW/XQlb7pWMl4sPQt1VJt7WARsJ0F+Z8ScJtsyn/Tp2gbily2/5VH6paOjw86anrrjhH9cTvBMwROlzLpdYvuszdKpb4dU="
