sudo: required
dist: trusty
services: docker

addons:
  apt:
    sources:
      - chef-stable-trusty
    packages:
      - chefdk

env:
  global:
  - KITCHEN_LOCAL_YAML=.kitchen.dokken.yml
  matrix:
  - KITCHEN_REGEXP=package-ubuntu-1404
  - KITCHEN_REGEXP=source-ubuntu-1404
  - KITCHEN_REGEXP=package-ubuntu-1604
  - KITCHEN_REGEXP=source-ubuntu-1604

matrix:
  fast_finish: true
  include:
    - script:
      - chef exec delivery local all

# Don't `bundle install` because we're using ChefDK
install: echo "skip bundle install"

before_install:
  - sudo apt-get update
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

before_script:
  - sudo iptables -L DOCKER || ( echo "DOCKER iptables chain missing" ; sudo iptables -N DOCKER )
  - eval "$(/opt/chefdk/bin/chef shell-init bash)"
  - chef gem install kitchen-dokken
  - chef gem install stove

script: kitchen verify ${KITCHEN_REGEXP}

notifications:
  email: false
  slack:
    secure: "cNz3S0Iw6IWQOzP4IIwSbqMjhPYNOwb6w/9/G1G6YcRTUDEtBY/BwJMdOyMsI568GU+D94oQa7OXswW/XQlb7pWMl4sPQt1VJt7WARsJ0F+Z8ScJtsyn/Tp2gbily2/5VH6paOjw86anrrjhH9cTvBMwROlzLpdYvuszdKpb4dU="
